version: '3'
services:

  account-db:
    image: postgres:14.2
    hostname: postgres-host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'